### ISSUE TITLE
SpartanController crashing due to access to controlfile

### ISSUE THREAD

**Issue by daveola** [fische17/SpartanController#2]
I love SpartanController, but I have been problems with it occasionally crashing, and it seems to be happening more often.

According to the debugger, it's hitting:

System.IO.IOException: 'The process cannot access the file '...<controlfile path>..' because it is being used by another process'

It seems that dropbox needs to handle the controlfile.txt file as well, is there an issue with the access to this file colliding?  Can we retry on this ioexception?

**Comment by Arylos07** [comment]
I know this is necroing an old issue, but I got my Vector today and this bug was super annoying. So I fixed it.

The only real fix I could find was by delaying how long to read the command. I did this by adding an Execution Delay variable to the program. Increasing this variable will increase how long the program waits for Dropbox to finish (default is 2 seconds). 

I'm not sure if there is an event for when a file is finished edited by Dropbox, hence the delay route. It's not the best solution, but it works for now. 

**EDIT:** because I don't have the manifest certificate, I did not make a new build. That will have to rely on @KyleJFischer to rebuild the software. I made my build by removing the certificate from the .csproj file. If a new version isn't rebuild, I do recommend following [these steps](https://stackoverflow.com/questions/11957295/unable-to-find-manifest-signing-certificate-in-the-certificate-store-even-wh), but just for your own private build.

**Comment by KyleJFischer** [comment]
Im necroing this again, will look into this, Hopefully I can get a build out there. I don't know if I still have that cert due to multiple reformatting of my computer. But plan on merging this in later this weekend (finally)
